services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pearlibl
    volumes:
      - todo_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - .:/src
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=todo_db;Username=postgres;Password=pearlibl
    command: >
      sh -c "
      dotnet tool install --global dotnet-ef --version 8.0.11 &&
      export PATH=\"$PATH:/root/.dotnet/tools\" &&
      dotnet ef database update
        --project ToDoWebApplication.Infrastructure
        --startup-project ToDoWebApplication
      "
  web:
    build: .
    depends_on:
      - migrate
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=todo_db;Username=postgres;Password=pearlibl
    ports:
      - "8080:8080"

volumes:
  todo_db_data:
